// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type OptionsLegacyParser } from '@hey-api/client-axios';
import type { ReadItemsV1ItemsGetError, ReadItemsV1ItemsGetResponse, ReadUserMeV1UsersMeGetError, ReadUserMeV1UsersMeGetResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Read Items
 */
export const readItemsV1ItemsGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadItemsV1ItemsGetResponse, ReadItemsV1ItemsGetError, ThrowOnError>({
        ...options,
        url: '/v1/items/'
    });
};

/**
 * Read User Me
 * Get current user.
 */
export const readUserMeV1UsersMeGet = <ThrowOnError extends boolean = false>(options?: OptionsLegacyParser<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<ReadUserMeV1UsersMeGetResponse, ReadUserMeV1UsersMeGetError, ThrowOnError>({
        ...options,
        url: '/v1/users/me'
    });
};