openapi: "3.0.0"
components:
  schemas:
    Project:
      allOf:
        - $ref: "#/components/schemas/NewProject"
        - required:
            - id
          properties:
            id:
              type: integer
              format: uint64
              description: Unique id of the project

    NewProject:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the project
        tag:
          type: string
          description: Type of the project

    Role:
      allOf:
        - $ref: "#/components/schemas/NewRole"
        - required:
            - id
          properties:
            id:
              type: integer
              format: uint64
              description: Unique id of the project

    NewRole:
      required:
        - name
      properties:
        name:
          type: string
          description: Name of the project
        tag:
          type: string
          description: Type of the project
