openapi: "3.0.0"
servers:
  - url: http://127.0.0.1
info:
  version: 1.0.0
  title: Swagger Projectstore
  description: A sample API that uses a projectstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: https://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - XUser: []
components:
  securitySchemes:
    XUser:
      type: apiKey
      name: x-user-name
      in: header
      description: "the custom authorization type"
paths:
  /v1/projects:
    $ref: "./paths/projects.yaml#/projects"
  /v1/projects/{id}:
    $ref: "./paths/projects.yaml#/projects_id"
  /v1/roles:
    $ref: "./paths/roles.yaml#/roles"
  /v1/roles/{id}:
    $ref: "./paths/roles.yaml#/roles_id"
  /v3:
    $ref: "./paths/keystone.yaml#/v3"
  /v3/auth/tokens:
    $ref: "./paths/keystone_tokens.yaml#/tokens"
