linters:
  enable-all: true
  disable:
    - gofumpt
    - exhaustruct
    - exhaustivestruct # depricated
    - exportloopref # depricated
    - dupl
    - ireturn

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/syunkitada/stadyapp)
  depguard:
    rules:
      Main:
        allow:
          - "$gostd"
          - github.com/stretchr/testify
          - github.com/DATA-DOG/go-sqlmock
          - gorm.io/gorm
          - github.com/go-sql-driver/mysql
          - github.com/labstack/echo/v4
          - github.com/labstack/gommon
          - github.com/oapi-codegen/echo-middleware
          - github.com/syunkitada/stadyapp
  mnd:
    ignored-numbers:
      - "0644"
  varnamelen:
    ignore-names:
      - db
      - tx
  revive:
    rules:
      - name: receiver-naming
        disabled: true
  wrapcheck:
    ignoreSigs:
      - tlog.Wrap
      - tlog.Bind
  stylecheck:
    checks:
      - "all"
      - "-ST1006"
