KeystoneApplicationCredential:
  type: object
  properties:
    id:
      type: string
      example: "58d61ff8e6e34accb35874016d1dba8b"
    name:
      type: string
      example: "monitoring"
    description:
      type: string
      example: "Application credential for monitoring."
    roles:
      type: array
      items:
        $ref: "./keystone_token.yaml#/KeystoneTokenRole"
    access_rules:
      type: array
      items:
        type: object
        properties:
          path:
            type: string
            example: "/v2.0/metrics"
          id:
            type: string
            format: uuid
            example: "07d719df00f349ef8de77d542edf010c"
          service:
            type: string
            example: "monitoring"
          method:
            type: string
            example: "GET"
    links:
      type: object
      properties:
        self:
          type: string
          format: uri
          example: "http://example.com/identity/v3/users/fd786d56402c4d1691372e7dee0d00b5/application_credentials/58d61ff8e6e34accb35874016d1dba8b"
    expires_at:
      type: string
      format: date-time
      example: "2018-02-27T18:30:59.000000"
    unrestricted:
      type: boolean
      example: false
    secret:
      type: string
      example: "rEaqvJka48mpv"
    project_id:
      type: string
      example: "231c62fb0fbd485b995e8b060c3f0d98"
  required:
    - id
    - name
    - roles
    - expires_at
    - secret
    - project_id

KeystoneApplicationCredentialResponse:
  type: object
  properties:
    application_credential:
      $ref: "#/KeystoneApplicationCredential"
  required:
    - application_credential

CreateKeystoneApplicationCredentialInput:
  type: object
  required:
    - application_credential
  properties:
    application_credential:
      type: object
      properties:
        roles:
          type: array
          items:
            type: string
          example: []
        name:
          type: string
          example: "service"
        unrestricted:
          type: boolean
          example: false
        secret:
          type: string
          nullable: true
          example: null
        expires_at:
          type: string
          nullable: true
          example: "2017-07-21T17:32:28"
        access_rules:
          type: array
          items:
            type: object
          example: []
        description:
          type: string
          nullable: true
          example: null
      required:
        - name
