Project:
  allOf:
    - $ref: "#/NewProject"
    - required:
        - id
      properties:
        id:
          type: integer
          format: uint64
          description: Unique id of the project

Projects:
  type: array
  items:
    $ref: "#/Project"

NewProject:
  required:
    - name
  properties:
    name:
      type: string
      description: Name of the project
    tag:
      type: string
      description: Type of the project
