application_credentials:
  post:
    tags: ["cli"]
    summary: Create a new keystone application credential
    description: Create a new keystone application credential
    operationId: createKeystoneApplicationCredential
    parameters:
      - name: user_id
        in: path
        description: ID of keystone user to fetch
        required: true
        schema:
          type: string
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../schemas/keystone_application_credential.yaml#/CreateKeystoneApplicationCredentialInput"
    responses:
      "200":
        description: keystone project response
        content:
          application/json:
            schema:
              $ref: "../schemas/keystone_application_credential.yaml#/KeystoneApplicationCredentialResponse"
      "4XX":
        description: unexpected error
        content:
          application/json:
            schema:
              $ref: "../../../../../libs/openapi_common/schemas.yaml#/components/schemas/Error"
      default:
        description: unexpected error
        content:
          application/json:
            schema:
              $ref: "../../../../../libs/openapi_common/schemas.yaml#/components/schemas/Error"
