openapi: "3.0.0"
servers:
  - url: http://127.0.0.1
info:
  version: 1.0.0
  title: Swagger Projectstore
  description: A sample API that uses a projectstore as an example to demonstrate features in the OpenAPI 3.0 specification
  termsOfService: https://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: apiteam@swagger.io
    url: https://swagger.io
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
security:
  - XAuthTokenHeader: []
components:
  securitySchemes:
    XUserIDHeader:
      type: apiKey
      name: x-user-id
      in: header
      description: "The custom authorization"
    XAuthTokenHeader:
      type: apiKey
      name: x-auth-token
      in: header
      description: "The custom authorization"
paths:
  /glance/v2:
    $ref: "./paths/glance.yaml#/glance"
  /glance/v2/images:
    $ref: "./paths/glance_images.yaml#/images"
  /glance/v2/images/{id}:
    $ref: "./paths/glance_images.yaml#/images_id"
  /glance/v2/images/{id}/file:
    $ref: "./paths/glance_images.yaml#/images_id_file"
  /glance/v2/schemas/image:
    $ref: "./paths/glance_schemas.yaml#/image"
  /nova/v2.1:
    $ref: "./paths/nova.yaml#/version"
  /nova/v2.1/os-services:
    $ref: "./paths/nova_services.yaml#/services"
  /nova/v2.1/servers:
    $ref: "./paths/nova_servers.yaml#/servers"
  /nova/v2.1/servers/{id}:
    $ref: "./paths/nova_servers.yaml#/servers_id"
  /nova/v2.1/servers/{id}/action:
    $ref: "./paths/nova_servers.yaml#/servers_id_action"
  /nova/v2.1/servers/detail:
    $ref: "./paths/nova_servers.yaml#/servers_detail"
  /nova/v2.1/flavors:
    $ref: "./paths/nova_flavors.yaml#/flavors"
  /nova/v2.1/flavors/detail:
    $ref: "./paths/nova_flavors.yaml#/flavors_detail"
  /nova/v2.1/flavors/{id}:
    $ref: "./paths/nova_flavors.yaml#/flavors_id"
  /nova/v2.1/os-server-external-events:
    $ref: "./paths/nova_os_server_external_events.yaml#/os_server_external_events"
  /neutron/v2.0:
    $ref: "./paths/neutron.yaml#/version"
  /neutron/v2.0/networks:
    $ref: "./paths/neutron_networks.yaml#/networks"
  /neutron/v2.0/networks/{id}:
    $ref: "./paths/neutron_networks.yaml#/networks_id"
  /neutron/v2.0/subnets:
    $ref: "./paths/neutron_subnets.yaml#/subnets"
  /neutron/v2.0/subnets/{id}:
    $ref: "./paths/neutron_subnets.yaml#/subnets_id"
  /neutron/v2.0/quotas/{project_id}:
    $ref: "./paths/neutron_quotas.yaml#/quotas_project_id"
  /neutron/v2.0/agents:
    $ref: "./paths/neutron_agents.yaml#/agents"
  /neutron/v2.0/ports:
    $ref: "./paths/neutron_ports.yaml#/ports"
  /neutron/v2.0/ports/{id}:
    $ref: "./paths/neutron_ports.yaml#/ports_id"
  /neutron/v2.0/security-groups:
    $ref: "./paths/neutron_security_groups.yaml#/security-groups"
  /neutron/v2.0/extensions:
    $ref: "./paths/neutron_extensions.yaml#/extensions"
  /placement:
    $ref: "./paths/placement.yaml#/version"
  /placement/:
    $ref: "./paths/placement.yaml#/version2"
  /placement/traits:
    $ref: "./paths/placement_traits.yaml#/traits"
  /placement/resource_providers:
    $ref: "./paths/placement_resource_providers.yaml#/resource_providers"
  /placement/resource_providers/{id}/allocations:
    $ref: "./paths/placement_resource_providers.yaml#/resource_providers_id_allocations"
  /placement/resource_providers/{id}/inventories:
    $ref: "./paths/placement_resource_providers.yaml#/resource_providers_id_inventories"
  /placement/resource_providers/{id}/aggregates:
    $ref: "./paths/placement_resource_providers.yaml#/resource_providers_id_aggregates"
  /placement/resource_providers/{id}/traits:
    $ref: "./paths/placement_resource_providers.yaml#/resource_providers_id_traits"
  /placement/allocations/{id}:
    $ref: "./paths/placement_allocations.yaml#/allocations_id"
  /placement/allocation_candidates:
    $ref: "./paths/placement_allocation_candidates.yaml#/allocation_candidates"
