version: "3"
services:
  openstack-allinone:
    container_name: openstack-allinone
    hostname: openstack-allinone
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./opt:/opt/openstack:ro"
    privileged: true
    cgroup_parent: docker.slice
    network_mode: host
