/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LayoutImport } from './routes/_layout'
import { Route as LayoutIndexImport } from './routes/_layout/index'
import { Route as LayoutIamIndexImport } from './routes/_layout/iam/index'
import { Route as LayoutComputeIndexImport } from './routes/_layout/compute/index'

// Create/Update Routes

const LayoutRoute = LayoutImport.update({
  id: '/_layout',
  getParentRoute: () => rootRoute,
} as any)

const LayoutIndexRoute = LayoutIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutIamIndexRoute = LayoutIamIndexImport.update({
  id: '/iam/',
  path: '/iam/',
  getParentRoute: () => LayoutRoute,
} as any)

const LayoutComputeIndexRoute = LayoutComputeIndexImport.update({
  id: '/compute/',
  path: '/compute/',
  getParentRoute: () => LayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutImport
      parentRoute: typeof rootRoute
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/compute/': {
      id: '/_layout/compute/'
      path: '/compute'
      fullPath: '/compute'
      preLoaderRoute: typeof LayoutComputeIndexImport
      parentRoute: typeof LayoutImport
    }
    '/_layout/iam/': {
      id: '/_layout/iam/'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof LayoutIamIndexImport
      parentRoute: typeof LayoutImport
    }
  }
}

// Create and export the route tree

interface LayoutRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutComputeIndexRoute: typeof LayoutComputeIndexRoute
  LayoutIamIndexRoute: typeof LayoutIamIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutComputeIndexRoute: LayoutComputeIndexRoute,
  LayoutIamIndexRoute: LayoutIamIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof LayoutRouteWithChildren
  '/': typeof LayoutIndexRoute
  '/compute': typeof LayoutComputeIndexRoute
  '/iam': typeof LayoutIamIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/compute': typeof LayoutComputeIndexRoute
  '/iam': typeof LayoutIamIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/compute/': typeof LayoutComputeIndexRoute
  '/_layout/iam/': typeof LayoutIamIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/compute' | '/iam'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/compute' | '/iam'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/compute/'
    | '/_layout/iam/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_layout"
      ]
    },
    "/_layout": {
      "filePath": "_layout.tsx",
      "children": [
        "/_layout/",
        "/_layout/compute/",
        "/_layout/iam/"
      ]
    },
    "/_layout/": {
      "filePath": "_layout/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/compute/": {
      "filePath": "_layout/compute/index.tsx",
      "parent": "/_layout"
    },
    "/_layout/iam/": {
      "filePath": "_layout/iam/index.tsx",
      "parent": "/_layout"
    }
  }
}
ROUTE_MANIFEST_END */
