// This file is auto-generated by @hey-api/openapi-ts

export type Item = {
    title: string;
    description?: (string | null);
    id?: string;
};

export type Items = {
    data: Array<Item>;
    count: number;
};

export type User = {
    name: string;
    email?: (string | null);
};

export type ReadItemsV1ItemsGetResponse = (Items);

export type ReadItemsV1ItemsGetError = unknown;

export type ReadUserMeV1UsersMeGetResponse = (User);

export type ReadUserMeV1UsersMeGetError = unknown;